default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_DB"] %>
  host: <%= ENV["POSTGRES_HOST"] %>

test:
  <<: *default

# production:
#   <<: *default
#   database: app_production
#   username: app
#   password: <%= ENV["APP_DATABASE_PASSWORD"] %>
